# Generated by Django 5.1.2 on 2024-11-04 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id producto')),
                ('nombreProducto', models.CharField(max_length=255, verbose_name='Nombre producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio producto')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen producto')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock producto')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id usuario')),
                ('nombreUsuario', models.CharField(max_length=20, verbose_name='Nombre usuario')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo usuario')),
                ('contrasena', models.CharField(max_length=255, verbose_name='Contrasena usuario')),
                ('contrasena2', models.CharField(max_length=255, verbose_name='Contrasena usuario 2')),
            ],
        ),
        migrations.CreateModel(
            name='tarea',
            fields=[
                ('idTarea', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tarea')),
                ('nombreTarea', models.CharField(max_length=100, verbose_name='Nombre tarea')),
                ('fechaInicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha inicio')),
                ('fechaTermino', models.DateTimeField(blank=True, null=True, verbose_name='Fecha término')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.usuario')),
            ],
        ),
    ]
