# Generated by Django 5.1.2 on 2024-12-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Root', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='duracion_contrato',
        ),
    ]
