# Generated by Django 5.1.2 on 2024-12-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Root', '0002_remove_cliente_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
    ]
