# Generated by Django 5.1.2 on 2024-11-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Root', '0003_cliente_alter_tarea_usuario_tarea_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('vendedor', 'Vendedor')], max_length=20),
        ),
    ]
