# Generated by Django 5.1.2 on 2024-12-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Root', '0003_remove_productos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='terminado',
            field=models.BooleanField(default=False, verbose_name='Terminado'),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
    ]
